/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * TL Analytics API
 * API для аналитики заказов
 * OpenAPI spec version: 1.0
 */

export type GetAnalyticsWorkshopsIncomingByBuildingsParams = {
/**
 * Начало периода (ISO 8601)
 */
date_from: string;
/**
 * Конец периода (ISO 8601)
 */
date_to: string;
/**
 * Если false - заказы ИЗ цехов (depart_loc), если true - заказы В цеха (goal_loc)
 */
isIn?: boolean;
};
