/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * TL Analytics API
 * API для аналитики заказов
 * OpenAPI spec version: 1.0
 */

export type GetAnalyticsDriversOrdersByTypesParams = {
/**
 * Начало периода (ISO 8601)
 */
date_from: string;
/**
 * Конец периода (ISO 8601)
 */
date_to: string;
/**
 * Если true - возвращает вес груза, если false - количество заказов
 */
isWithWeight?: boolean;
};
