/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * TL Analytics API
 * API для аналитики заказов
 * OpenAPI spec version: 1.0
 */

/**
 * float для веса, int для количества
 */
export type ModelDriverOrdersResponseCargoTypes = {[key: string]: number};
