/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * TechLogist API
 * API сервер для управления логистикой
 * OpenAPI spec version: 1.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  GetCheckParams,
  GithubComVeresusTlApiInternalModelCheckResponse,
  GithubComVeresusTlApiInternalModelErrorResponse
} from '.././model';

import { apiClient } from '../../../utils/customAxios';




/**
 * Проверка подключения к сервису
 * @summary Проверка подключения к сервису
 */
export const getCheck = (
    params?: GetCheckParams,
 signal?: AbortSignal
) => {
      
      
      return apiClient<GithubComVeresusTlApiInternalModelCheckResponse>(
      {url: `/check`, method: 'GET',
        params, signal
    },
      );
    }
  



export const getGetCheckQueryKey = (params?: GetCheckParams,) => {
    return [
    `/check`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetCheckQueryOptions = <TData = Awaited<ReturnType<typeof getCheck>>, TError = GithubComVeresusTlApiInternalModelErrorResponse>(params?: GetCheckParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCheck>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetCheckQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getCheck>>> = ({ signal }) => getCheck(params, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getCheck>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetCheckQueryResult = NonNullable<Awaited<ReturnType<typeof getCheck>>>
export type GetCheckQueryError = GithubComVeresusTlApiInternalModelErrorResponse


export function useGetCheck<TData = Awaited<ReturnType<typeof getCheck>>, TError = GithubComVeresusTlApiInternalModelErrorResponse>(
 params: undefined |  GetCheckParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCheck>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCheck>>,
          TError,
          Awaited<ReturnType<typeof getCheck>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetCheck<TData = Awaited<ReturnType<typeof getCheck>>, TError = GithubComVeresusTlApiInternalModelErrorResponse>(
 params?: GetCheckParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCheck>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCheck>>,
          TError,
          Awaited<ReturnType<typeof getCheck>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetCheck<TData = Awaited<ReturnType<typeof getCheck>>, TError = GithubComVeresusTlApiInternalModelErrorResponse>(
 params?: GetCheckParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCheck>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Проверка подключения к сервису
 */

export function useGetCheck<TData = Awaited<ReturnType<typeof getCheck>>, TError = GithubComVeresusTlApiInternalModelErrorResponse>(
 params?: GetCheckParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCheck>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetCheckQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




