/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * TechLogist API
 * API сервер для управления логистикой
 * OpenAPI spec version: 1.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  GithubComVeresusTlApiInternalModelDropDownListInfoResponse,
  GithubComVeresusTlApiInternalModelErrorResponse
} from '../model';

import { apiClient } from '../../../utils/customAxios';




/**
 * Возвращает список типов грузов и связей подразделений и зданий
 * @summary Возвращает список типов грузов и связей подразделений и зданий
 */
export const getRefDropdownListInfo = (
    
 signal?: AbortSignal
) => {
      
      
      return apiClient<GithubComVeresusTlApiInternalModelDropDownListInfoResponse>(
      {url: `/ref/dropdown-list-info`, method: 'GET', signal
    },
      );
    }
  



export const getGetRefDropdownListInfoQueryKey = () => {
    return [
    `/ref/dropdown-list-info`
    ] as const;
    }

    
export const getGetRefDropdownListInfoQueryOptions = <TData = Awaited<ReturnType<typeof getRefDropdownListInfo>>, TError = GithubComVeresusTlApiInternalModelErrorResponse>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getRefDropdownListInfo>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetRefDropdownListInfoQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getRefDropdownListInfo>>> = ({ signal }) => getRefDropdownListInfo(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getRefDropdownListInfo>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetRefDropdownListInfoQueryResult = NonNullable<Awaited<ReturnType<typeof getRefDropdownListInfo>>>
export type GetRefDropdownListInfoQueryError = GithubComVeresusTlApiInternalModelErrorResponse


export function useGetRefDropdownListInfo<TData = Awaited<ReturnType<typeof getRefDropdownListInfo>>, TError = GithubComVeresusTlApiInternalModelErrorResponse>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getRefDropdownListInfo>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getRefDropdownListInfo>>,
          TError,
          Awaited<ReturnType<typeof getRefDropdownListInfo>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetRefDropdownListInfo<TData = Awaited<ReturnType<typeof getRefDropdownListInfo>>, TError = GithubComVeresusTlApiInternalModelErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getRefDropdownListInfo>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getRefDropdownListInfo>>,
          TError,
          Awaited<ReturnType<typeof getRefDropdownListInfo>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetRefDropdownListInfo<TData = Awaited<ReturnType<typeof getRefDropdownListInfo>>, TError = GithubComVeresusTlApiInternalModelErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getRefDropdownListInfo>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Возвращает список типов грузов и связей подразделений и зданий
 */

export function useGetRefDropdownListInfo<TData = Awaited<ReturnType<typeof getRefDropdownListInfo>>, TError = GithubComVeresusTlApiInternalModelErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getRefDropdownListInfo>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetRefDropdownListInfoQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




