/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * TechLogist API
 * API сервер для управления логистикой
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  DtoOrder,
  DtoOrderCreate,
  DtoOrderForUpdateResponse,
  DtoOrderUpdate,
  GithubComVeresusTlApiInternalClientsTlOrdersClientDtoPersonalCatalogResponse,
  GithubComVeresusTlApiInternalModelErrorResponse,
  GithubComVeresusTlApiInternalModelMessageResponse,
  GithubComVeresusTlApiInternalModelOrdersResponse,
  GithubComVeresusTlApiInternalModelUploadPhoto,
  PostOrdersPhotoUploadBody
} from '.././model';

import { apiClient } from '../../utils/customAxios';




/**
 * Возвращает список всех актуальных заявок
 * @summary Получить все актуальные заявки
 */
export const getOrdersActual = (
    
 signal?: AbortSignal
) => {
      
      
      return apiClient<GithubComVeresusTlApiInternalModelOrdersResponse>(
      {url: `/orders/actual`, method: 'GET', signal
    },
      );
    }
  



export const getGetOrdersActualQueryKey = () => {
    return [
    `/orders/actual`
    ] as const;
    }

    
export const getGetOrdersActualQueryOptions = <TData = Awaited<ReturnType<typeof getOrdersActual>>, TError = GithubComVeresusTlApiInternalModelErrorResponse>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getOrdersActual>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetOrdersActualQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getOrdersActual>>> = ({ signal }) => getOrdersActual(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getOrdersActual>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetOrdersActualQueryResult = NonNullable<Awaited<ReturnType<typeof getOrdersActual>>>
export type GetOrdersActualQueryError = GithubComVeresusTlApiInternalModelErrorResponse


export function useGetOrdersActual<TData = Awaited<ReturnType<typeof getOrdersActual>>, TError = GithubComVeresusTlApiInternalModelErrorResponse>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getOrdersActual>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getOrdersActual>>,
          TError,
          Awaited<ReturnType<typeof getOrdersActual>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetOrdersActual<TData = Awaited<ReturnType<typeof getOrdersActual>>, TError = GithubComVeresusTlApiInternalModelErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getOrdersActual>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getOrdersActual>>,
          TError,
          Awaited<ReturnType<typeof getOrdersActual>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetOrdersActual<TData = Awaited<ReturnType<typeof getOrdersActual>>, TError = GithubComVeresusTlApiInternalModelErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getOrdersActual>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Получить все актуальные заявки
 */

export function useGetOrdersActual<TData = Awaited<ReturnType<typeof getOrdersActual>>, TError = GithubComVeresusTlApiInternalModelErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getOrdersActual>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetOrdersActualQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * Создает новую заявку в системе
 * @summary Создать новую заявку
 */
export const postOrdersCreate = (
    dtoOrderCreate: DtoOrderCreate,
 signal?: AbortSignal
) => {
      
      
      return apiClient<GithubComVeresusTlApiInternalModelMessageResponse>(
      {url: `/orders/create`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: dtoOrderCreate, signal
    },
      );
    }
  


export const getPostOrdersCreateMutationOptions = <TError = GithubComVeresusTlApiInternalModelErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postOrdersCreate>>, TError,{data: DtoOrderCreate}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof postOrdersCreate>>, TError,{data: DtoOrderCreate}, TContext> => {

const mutationKey = ['postOrdersCreate'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postOrdersCreate>>, {data: DtoOrderCreate}> = (props) => {
          const {data} = props ?? {};

          return  postOrdersCreate(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostOrdersCreateMutationResult = NonNullable<Awaited<ReturnType<typeof postOrdersCreate>>>
    export type PostOrdersCreateMutationBody = DtoOrderCreate
    export type PostOrdersCreateMutationError = GithubComVeresusTlApiInternalModelErrorResponse

    /**
 * @summary Создать новую заявку
 */
export const usePostOrdersCreate = <TError = GithubComVeresusTlApiInternalModelErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postOrdersCreate>>, TError,{data: DtoOrderCreate}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postOrdersCreate>>,
        TError,
        {data: DtoOrderCreate},
        TContext
      > => {

      const mutationOptions = getPostOrdersCreateMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Возвращает сеты заказов (в работе, новые, завершенные)
 * @summary Личный каталог заказов
 */
export const getOrdersPersonalCatalog = (
    
 signal?: AbortSignal
) => {
      
      
      return apiClient<GithubComVeresusTlApiInternalClientsTlOrdersClientDtoPersonalCatalogResponse>(
      {url: `/orders/personal/catalog`, method: 'GET', signal
    },
      );
    }
  



export const getGetOrdersPersonalCatalogQueryKey = () => {
    return [
    `/orders/personal/catalog`
    ] as const;
    }

    
export const getGetOrdersPersonalCatalogQueryOptions = <TData = Awaited<ReturnType<typeof getOrdersPersonalCatalog>>, TError = GithubComVeresusTlApiInternalModelErrorResponse>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getOrdersPersonalCatalog>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetOrdersPersonalCatalogQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getOrdersPersonalCatalog>>> = ({ signal }) => getOrdersPersonalCatalog(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getOrdersPersonalCatalog>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetOrdersPersonalCatalogQueryResult = NonNullable<Awaited<ReturnType<typeof getOrdersPersonalCatalog>>>
export type GetOrdersPersonalCatalogQueryError = GithubComVeresusTlApiInternalModelErrorResponse


export function useGetOrdersPersonalCatalog<TData = Awaited<ReturnType<typeof getOrdersPersonalCatalog>>, TError = GithubComVeresusTlApiInternalModelErrorResponse>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getOrdersPersonalCatalog>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getOrdersPersonalCatalog>>,
          TError,
          Awaited<ReturnType<typeof getOrdersPersonalCatalog>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetOrdersPersonalCatalog<TData = Awaited<ReturnType<typeof getOrdersPersonalCatalog>>, TError = GithubComVeresusTlApiInternalModelErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getOrdersPersonalCatalog>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getOrdersPersonalCatalog>>,
          TError,
          Awaited<ReturnType<typeof getOrdersPersonalCatalog>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetOrdersPersonalCatalog<TData = Awaited<ReturnType<typeof getOrdersPersonalCatalog>>, TError = GithubComVeresusTlApiInternalModelErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getOrdersPersonalCatalog>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Личный каталог заказов
 */

export function useGetOrdersPersonalCatalog<TData = Awaited<ReturnType<typeof getOrdersPersonalCatalog>>, TError = GithubComVeresusTlApiInternalModelErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getOrdersPersonalCatalog>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetOrdersPersonalCatalogQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * Загружает фотографию в систему
 * @summary Загрузить фотографию
 */
export const postOrdersPhotoUpload = (
    postOrdersPhotoUploadBody: PostOrdersPhotoUploadBody,
 signal?: AbortSignal
) => {
      
      const formData = new FormData();
formData.append(`photo`, postOrdersPhotoUploadBody.photo)

      return apiClient<GithubComVeresusTlApiInternalModelUploadPhoto>(
      {url: `/orders/photo/upload`, method: 'POST',
      headers: {'Content-Type': 'multipart/form-data', },
       data: formData, signal
    },
      );
    }
  


export const getPostOrdersPhotoUploadMutationOptions = <TError = GithubComVeresusTlApiInternalModelErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postOrdersPhotoUpload>>, TError,{data: PostOrdersPhotoUploadBody}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof postOrdersPhotoUpload>>, TError,{data: PostOrdersPhotoUploadBody}, TContext> => {

const mutationKey = ['postOrdersPhotoUpload'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postOrdersPhotoUpload>>, {data: PostOrdersPhotoUploadBody}> = (props) => {
          const {data} = props ?? {};

          return  postOrdersPhotoUpload(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostOrdersPhotoUploadMutationResult = NonNullable<Awaited<ReturnType<typeof postOrdersPhotoUpload>>>
    export type PostOrdersPhotoUploadMutationBody = PostOrdersPhotoUploadBody
    export type PostOrdersPhotoUploadMutationError = GithubComVeresusTlApiInternalModelErrorResponse

    /**
 * @summary Загрузить фотографию
 */
export const usePostOrdersPhotoUpload = <TError = GithubComVeresusTlApiInternalModelErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postOrdersPhotoUpload>>, TError,{data: PostOrdersPhotoUploadBody}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postOrdersPhotoUpload>>,
        TError,
        {data: PostOrdersPhotoUploadBody},
        TContext
      > => {

      const mutationOptions = getPostOrdersPhotoUploadMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Отдает файл фотографии по UUID
 * @summary Получить файл фотографии
 */
export const getOrdersPhotoId = (
    id: string,
 signal?: AbortSignal
) => {
      
      
      return apiClient<Blob>(
      {url: `/orders/photo/${id}`, method: 'GET',
        responseType: 'blob', signal
    },
      );
    }
  



export const getGetOrdersPhotoIdQueryKey = (id?: string,) => {
    return [
    `/orders/photo/${id}`
    ] as const;
    }

    
export const getGetOrdersPhotoIdQueryOptions = <TData = Awaited<ReturnType<typeof getOrdersPhotoId>>, TError = GithubComVeresusTlApiInternalModelErrorResponse>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getOrdersPhotoId>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetOrdersPhotoIdQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getOrdersPhotoId>>> = ({ signal }) => getOrdersPhotoId(id, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getOrdersPhotoId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetOrdersPhotoIdQueryResult = NonNullable<Awaited<ReturnType<typeof getOrdersPhotoId>>>
export type GetOrdersPhotoIdQueryError = GithubComVeresusTlApiInternalModelErrorResponse


export function useGetOrdersPhotoId<TData = Awaited<ReturnType<typeof getOrdersPhotoId>>, TError = GithubComVeresusTlApiInternalModelErrorResponse>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getOrdersPhotoId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getOrdersPhotoId>>,
          TError,
          Awaited<ReturnType<typeof getOrdersPhotoId>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetOrdersPhotoId<TData = Awaited<ReturnType<typeof getOrdersPhotoId>>, TError = GithubComVeresusTlApiInternalModelErrorResponse>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getOrdersPhotoId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getOrdersPhotoId>>,
          TError,
          Awaited<ReturnType<typeof getOrdersPhotoId>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetOrdersPhotoId<TData = Awaited<ReturnType<typeof getOrdersPhotoId>>, TError = GithubComVeresusTlApiInternalModelErrorResponse>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getOrdersPhotoId>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Получить файл фотографии
 */

export function useGetOrdersPhotoId<TData = Awaited<ReturnType<typeof getOrdersPhotoId>>, TError = GithubComVeresusTlApiInternalModelErrorResponse>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getOrdersPhotoId>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetOrdersPhotoIdQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * Удаляет фотографию из системы
 * @summary Удалить фотографию
 */
export const deleteOrdersPhotoId = (
    id: string,
 ) => {
      
      
      return apiClient<GithubComVeresusTlApiInternalModelMessageResponse>(
      {url: `/orders/photo/${id}`, method: 'DELETE'
    },
      );
    }
  


export const getDeleteOrdersPhotoIdMutationOptions = <TError = GithubComVeresusTlApiInternalModelErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteOrdersPhotoId>>, TError,{id: string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof deleteOrdersPhotoId>>, TError,{id: string}, TContext> => {

const mutationKey = ['deleteOrdersPhotoId'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteOrdersPhotoId>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  deleteOrdersPhotoId(id,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteOrdersPhotoIdMutationResult = NonNullable<Awaited<ReturnType<typeof deleteOrdersPhotoId>>>
    
    export type DeleteOrdersPhotoIdMutationError = GithubComVeresusTlApiInternalModelErrorResponse

    /**
 * @summary Удалить фотографию
 */
export const useDeleteOrdersPhotoId = <TError = GithubComVeresusTlApiInternalModelErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteOrdersPhotoId>>, TError,{id: string}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteOrdersPhotoId>>,
        TError,
        {id: string},
        TContext
      > => {

      const mutationOptions = getDeleteOrdersPhotoIdMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Возвращает заявку с данными для обновления
 * @summary Получить заявку для обновления
 */
export const getOrdersUpdateId = (
    id: number,
 signal?: AbortSignal
) => {
      
      
      return apiClient<DtoOrderForUpdateResponse>(
      {url: `/orders/update/${id}`, method: 'GET', signal
    },
      );
    }
  



export const getGetOrdersUpdateIdQueryKey = (id?: number,) => {
    return [
    `/orders/update/${id}`
    ] as const;
    }

    
export const getGetOrdersUpdateIdQueryOptions = <TData = Awaited<ReturnType<typeof getOrdersUpdateId>>, TError = GithubComVeresusTlApiInternalModelErrorResponse>(id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getOrdersUpdateId>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetOrdersUpdateIdQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getOrdersUpdateId>>> = ({ signal }) => getOrdersUpdateId(id, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getOrdersUpdateId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetOrdersUpdateIdQueryResult = NonNullable<Awaited<ReturnType<typeof getOrdersUpdateId>>>
export type GetOrdersUpdateIdQueryError = GithubComVeresusTlApiInternalModelErrorResponse


export function useGetOrdersUpdateId<TData = Awaited<ReturnType<typeof getOrdersUpdateId>>, TError = GithubComVeresusTlApiInternalModelErrorResponse>(
 id: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getOrdersUpdateId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getOrdersUpdateId>>,
          TError,
          Awaited<ReturnType<typeof getOrdersUpdateId>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetOrdersUpdateId<TData = Awaited<ReturnType<typeof getOrdersUpdateId>>, TError = GithubComVeresusTlApiInternalModelErrorResponse>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getOrdersUpdateId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getOrdersUpdateId>>,
          TError,
          Awaited<ReturnType<typeof getOrdersUpdateId>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetOrdersUpdateId<TData = Awaited<ReturnType<typeof getOrdersUpdateId>>, TError = GithubComVeresusTlApiInternalModelErrorResponse>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getOrdersUpdateId>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Получить заявку для обновления
 */

export function useGetOrdersUpdateId<TData = Awaited<ReturnType<typeof getOrdersUpdateId>>, TError = GithubComVeresusTlApiInternalModelErrorResponse>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getOrdersUpdateId>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetOrdersUpdateIdQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * Возвращает информацию о заявке по её ID
 * @summary Получить заявку по ID
 */
export const getOrdersId = (
    id: number,
 signal?: AbortSignal
) => {
      
      
      return apiClient<DtoOrder>(
      {url: `/orders/${id}`, method: 'GET', signal
    },
      );
    }
  



export const getGetOrdersIdQueryKey = (id?: number,) => {
    return [
    `/orders/${id}`
    ] as const;
    }

    
export const getGetOrdersIdQueryOptions = <TData = Awaited<ReturnType<typeof getOrdersId>>, TError = GithubComVeresusTlApiInternalModelErrorResponse>(id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getOrdersId>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetOrdersIdQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getOrdersId>>> = ({ signal }) => getOrdersId(id, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getOrdersId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetOrdersIdQueryResult = NonNullable<Awaited<ReturnType<typeof getOrdersId>>>
export type GetOrdersIdQueryError = GithubComVeresusTlApiInternalModelErrorResponse


export function useGetOrdersId<TData = Awaited<ReturnType<typeof getOrdersId>>, TError = GithubComVeresusTlApiInternalModelErrorResponse>(
 id: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getOrdersId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getOrdersId>>,
          TError,
          Awaited<ReturnType<typeof getOrdersId>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetOrdersId<TData = Awaited<ReturnType<typeof getOrdersId>>, TError = GithubComVeresusTlApiInternalModelErrorResponse>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getOrdersId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getOrdersId>>,
          TError,
          Awaited<ReturnType<typeof getOrdersId>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetOrdersId<TData = Awaited<ReturnType<typeof getOrdersId>>, TError = GithubComVeresusTlApiInternalModelErrorResponse>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getOrdersId>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Получить заявку по ID
 */

export function useGetOrdersId<TData = Awaited<ReturnType<typeof getOrdersId>>, TError = GithubComVeresusTlApiInternalModelErrorResponse>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getOrdersId>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetOrdersIdQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * Обновляет существующую заявку
 * @summary Обновить заявку
 */
export const patchOrdersId = (
    id: number,
    dtoOrderUpdate: DtoOrderUpdate,
 ) => {
      
      
      return apiClient<GithubComVeresusTlApiInternalModelMessageResponse>(
      {url: `/orders/${id}`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: dtoOrderUpdate
    },
      );
    }
  


export const getPatchOrdersIdMutationOptions = <TError = GithubComVeresusTlApiInternalModelErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchOrdersId>>, TError,{id: number;data: DtoOrderUpdate}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof patchOrdersId>>, TError,{id: number;data: DtoOrderUpdate}, TContext> => {

const mutationKey = ['patchOrdersId'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof patchOrdersId>>, {id: number;data: DtoOrderUpdate}> = (props) => {
          const {id,data} = props ?? {};

          return  patchOrdersId(id,data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PatchOrdersIdMutationResult = NonNullable<Awaited<ReturnType<typeof patchOrdersId>>>
    export type PatchOrdersIdMutationBody = DtoOrderUpdate
    export type PatchOrdersIdMutationError = GithubComVeresusTlApiInternalModelErrorResponse

    /**
 * @summary Обновить заявку
 */
export const usePatchOrdersId = <TError = GithubComVeresusTlApiInternalModelErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchOrdersId>>, TError,{id: number;data: DtoOrderUpdate}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof patchOrdersId>>,
        TError,
        {id: number;data: DtoOrderUpdate},
        TContext
      > => {

      const mutationOptions = getPatchOrdersIdMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Принимает заявку водителем
 * @summary Принять заявку
 */
export const patchOrdersIdAccept = (
    id: number,
 ) => {
      
      
      return apiClient<GithubComVeresusTlApiInternalModelMessageResponse>(
      {url: `/orders/${id}/accept`, method: 'PATCH'
    },
      );
    }
  


export const getPatchOrdersIdAcceptMutationOptions = <TError = GithubComVeresusTlApiInternalModelErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchOrdersIdAccept>>, TError,{id: number}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof patchOrdersIdAccept>>, TError,{id: number}, TContext> => {

const mutationKey = ['patchOrdersIdAccept'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof patchOrdersIdAccept>>, {id: number}> = (props) => {
          const {id} = props ?? {};

          return  patchOrdersIdAccept(id,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PatchOrdersIdAcceptMutationResult = NonNullable<Awaited<ReturnType<typeof patchOrdersIdAccept>>>
    
    export type PatchOrdersIdAcceptMutationError = GithubComVeresusTlApiInternalModelErrorResponse

    /**
 * @summary Принять заявку
 */
export const usePatchOrdersIdAccept = <TError = GithubComVeresusTlApiInternalModelErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchOrdersIdAccept>>, TError,{id: number}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof patchOrdersIdAccept>>,
        TError,
        {id: number},
        TContext
      > => {

      const mutationOptions = getPatchOrdersIdAcceptMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Отменяет заявку
 * @summary Отменить заявку
 */
export const patchOrdersIdCancel = (
    id: number,
 ) => {
      
      
      return apiClient<GithubComVeresusTlApiInternalModelMessageResponse>(
      {url: `/orders/${id}/cancel`, method: 'PATCH'
    },
      );
    }
  


export const getPatchOrdersIdCancelMutationOptions = <TError = GithubComVeresusTlApiInternalModelErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchOrdersIdCancel>>, TError,{id: number}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof patchOrdersIdCancel>>, TError,{id: number}, TContext> => {

const mutationKey = ['patchOrdersIdCancel'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof patchOrdersIdCancel>>, {id: number}> = (props) => {
          const {id} = props ?? {};

          return  patchOrdersIdCancel(id,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PatchOrdersIdCancelMutationResult = NonNullable<Awaited<ReturnType<typeof patchOrdersIdCancel>>>
    
    export type PatchOrdersIdCancelMutationError = GithubComVeresusTlApiInternalModelErrorResponse

    /**
 * @summary Отменить заявку
 */
export const usePatchOrdersIdCancel = <TError = GithubComVeresusTlApiInternalModelErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchOrdersIdCancel>>, TError,{id: number}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof patchOrdersIdCancel>>,
        TError,
        {id: number},
        TContext
      > => {

      const mutationOptions = getPatchOrdersIdCancelMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Завершает заявку
 * @summary Завершить заявку
 */
export const patchOrdersIdComplete = (
    id: number,
 ) => {
      
      
      return apiClient<GithubComVeresusTlApiInternalModelMessageResponse>(
      {url: `/orders/${id}/complete`, method: 'PATCH'
    },
      );
    }
  


export const getPatchOrdersIdCompleteMutationOptions = <TError = GithubComVeresusTlApiInternalModelErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchOrdersIdComplete>>, TError,{id: number}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof patchOrdersIdComplete>>, TError,{id: number}, TContext> => {

const mutationKey = ['patchOrdersIdComplete'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof patchOrdersIdComplete>>, {id: number}> = (props) => {
          const {id} = props ?? {};

          return  patchOrdersIdComplete(id,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PatchOrdersIdCompleteMutationResult = NonNullable<Awaited<ReturnType<typeof patchOrdersIdComplete>>>
    
    export type PatchOrdersIdCompleteMutationError = GithubComVeresusTlApiInternalModelErrorResponse

    /**
 * @summary Завершить заявку
 */
export const usePatchOrdersIdComplete = <TError = GithubComVeresusTlApiInternalModelErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchOrdersIdComplete>>, TError,{id: number}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof patchOrdersIdComplete>>,
        TError,
        {id: number},
        TContext
      > => {

      const mutationOptions = getPatchOrdersIdCompleteMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Отклоняет заявку водителем
 * @summary Отклонить заявку
 */
export const patchOrdersIdReject = (
    id: number,
 ) => {
      
      
      return apiClient<GithubComVeresusTlApiInternalModelMessageResponse>(
      {url: `/orders/${id}/reject`, method: 'PATCH'
    },
      );
    }
  


export const getPatchOrdersIdRejectMutationOptions = <TError = GithubComVeresusTlApiInternalModelErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchOrdersIdReject>>, TError,{id: number}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof patchOrdersIdReject>>, TError,{id: number}, TContext> => {

const mutationKey = ['patchOrdersIdReject'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof patchOrdersIdReject>>, {id: number}> = (props) => {
          const {id} = props ?? {};

          return  patchOrdersIdReject(id,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PatchOrdersIdRejectMutationResult = NonNullable<Awaited<ReturnType<typeof patchOrdersIdReject>>>
    
    export type PatchOrdersIdRejectMutationError = GithubComVeresusTlApiInternalModelErrorResponse

    /**
 * @summary Отклонить заявку
 */
export const usePatchOrdersIdReject = <TError = GithubComVeresusTlApiInternalModelErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchOrdersIdReject>>, TError,{id: number}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof patchOrdersIdReject>>,
        TError,
        {id: number},
        TContext
      > => {

      const mutationOptions = getPatchOrdersIdRejectMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    