/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * TechLogist API
 * API сервер для управления логистикой
 * OpenAPI spec version: 1.0
 */

/**
 * DTO для обновления заявки
 */
export interface DtoOrderUpdate {
  cargo_description?: string;
  cargo_name?: string;
  cargo_type_id?: number;
  cargo_weight?: number;
  depart_loc?: number;
  goal_loc?: number;
  id: number;
  is_urgent?: boolean;
  photo_id?: string;
  time?: string;
}
