/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * TechLogist API
 * API сервер для управления логистикой
 * OpenAPI spec version: 1.0
 */

/**
 * Модель заявки
 */
export interface DtoOrder {
  cargo_description?: string;
  cargo_name?: string;
  cargo_type_id?: number;
  cargo_type_snapshot?: string;
  cargo_weight?: number;
  completion_time?: string;
  create_order_time?: string;
  depart_loc?: number;
  dispatcher_id?: number;
  driver_id?: number;
  driver_rate?: number;
  goal_loc?: number;
  id?: number;
  is_postponed?: boolean;
  is_urgent?: boolean;
  order_status_id?: number;
  photo_id?: string;
  pickup_time?: string;
  time?: string;
}
