/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * TechLogist API
 * API сервер для управления логистикой
 * OpenAPI spec version: 1.0
 */
import type { DtoRoleStatic } from './dtoRoleStatic';

/**
 * DTO для передачи данных регистрации
 */
export interface DtoRegisterRequest {
  fio?: string;
  login?: string;
  password?: string;
  phone?: string;
  role?: DtoRoleStatic;
  role_password?: string;
}
