/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * TechLogist API
 * API сервер для управления логистикой
 * OpenAPI spec version: 1.0
 */

/**
 * DTO для обновления информации о пользователе
 */
export interface DtoUserUpdate {
  fio?: string;
  login?: string;
  password?: string;
  phone?: string;
}
