/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * TechLogist API
 * API сервер для управления логистикой
 * OpenAPI spec version: 1.0
 */

/**
 * Модель пользователя
 */
export interface DtoUserForResponse {
  fio?: string;
  login?: string;
  phone?: string;
  public_id?: string;
  role_id?: string;
  role_name?: string;
}
