/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * TechLogist API
 * API сервер для управления логистикой
 * OpenAPI spec version: 1.0
 */

/**
 * DTO для передачи ошибки в ответе
 */
export interface GithubComVeresusTlApiInternalModelErrorResponse {
  details?: string;
  error?: string;
}
