/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * TechLogist API
 * API сервер для управления логистикой
 * OpenAPI spec version: 1.0
 */

/**
 * Мапа связей подразделений и зданий
 */
export interface GithubComVeresusTlApiInternalModelDepartmentBuildingMap {[key: string]: string}
