/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * TechLogist API
 * API сервер для управления логистикой
 * OpenAPI spec version: 1.0
 */

/**
 * DTO для передачи photo_id загруженного фото
 */
export interface GithubComVeresusTlApiInternalModelUploadPhoto {
  message?: string;
  photo_id?: string;
}
