/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * TechLogist API
 * API сервер для управления логистикой
 * OpenAPI spec version: 1.0
 */

export type GithubComVeresusTlApiInternalClientsTlOrdersClientDtoOrderOutStatus = typeof GithubComVeresusTlApiInternalClientsTlOrdersClientDtoOrderOutStatus[keyof typeof GithubComVeresusTlApiInternalClientsTlOrdersClientDtoOrderOutStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GithubComVeresusTlApiInternalClientsTlOrdersClientDtoOrderOutStatus = {
  ACCEPT: 'Принят',
  CANCEL: 'Отменен',
  COMPLETE: 'Выполнен',
  NEW: 'Новый',
  UNKNOWN: 'Неизвестно',
} as const;
