/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * TechLogist API
 * API сервер для управления логистикой
 * OpenAPI spec version: 1.0
 */

/**
 * DTO для передачи простого сообщения в ответе
 */
export interface GithubComVeresusTlApiInternalModelMessageResponse {
  message?: string;
}
