/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * TechLogist API
 * API сервер для управления логистикой
 * OpenAPI spec version: 1.0
 */
import type { GithubComVeresusTlApiInternalModelCargoTypeMap } from './githubComVeresusTlApiInternalModelCargoTypeMap';
import type { GithubComVeresusTlApiInternalModelDepartmentBuildingMap } from './githubComVeresusTlApiInternalModelDepartmentBuildingMap';

/**
 * DTO для передачи списка типов грузов и связей подразделений и зданий
 */
export interface GithubComVeresusTlApiInternalModelDropDownListInfoResponse {
  cargo_types?: GithubComVeresusTlApiInternalModelCargoTypeMap;
  dep_builds?: GithubComVeresusTlApiInternalModelDepartmentBuildingMap;
}
