/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * TechLogist API
 * API сервер для управления логистикой
 * OpenAPI spec version: 1.0
 */
import type { GithubComVeresusTlApiInternalClientsTlOrdersClientDtoPersonalCatalogSet } from './githubComVeresusTlApiInternalClientsTlOrdersClientDtoPersonalCatalogSet';

export interface GithubComVeresusTlApiInternalClientsTlOrdersClientDtoPersonalCatalogResponse {
  completed?: GithubComVeresusTlApiInternalClientsTlOrdersClientDtoPersonalCatalogSet;
  in_work?: GithubComVeresusTlApiInternalClientsTlOrdersClientDtoPersonalCatalogSet;
  new?: GithubComVeresusTlApiInternalClientsTlOrdersClientDtoPersonalCatalogSet;
}
