/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * TechLogist API
 * API сервер для управления логистикой
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  DtoLoginRequest,
  DtoRegisterRequest,
  DtoUserForResponse,
  DtoUserUpdate,
  GetPublicAuthCheckLoginLogin400,
  GetPublicAuthCheckLoginLogin500,
  GithubComVeresusTlApiInternalModelErrorResponse,
  GithubComVeresusTlApiInternalModelMessageResponse
} from '.././model';

import { apiClient } from '../../../utils/customAxios';




/**
 * Возвращает информацию о пользователе по его ID (int или UUID)
 * @summary Получить пользователя по ID
 */
export const getIdentUsersId = (
    id: string,
 signal?: AbortSignal
) => {
      
      
      return apiClient<DtoUserForResponse>(
      {url: `/ident/users/${id}`, method: 'GET', signal
    },
      );
    }
  



export const getGetIdentUsersIdQueryKey = (id?: string,) => {
    return [
    `/ident/users/${id}`
    ] as const;
    }

    
export const getGetIdentUsersIdQueryOptions = <TData = Awaited<ReturnType<typeof getIdentUsersId>>, TError = GithubComVeresusTlApiInternalModelErrorResponse>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getIdentUsersId>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetIdentUsersIdQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getIdentUsersId>>> = ({ signal }) => getIdentUsersId(id, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getIdentUsersId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetIdentUsersIdQueryResult = NonNullable<Awaited<ReturnType<typeof getIdentUsersId>>>
export type GetIdentUsersIdQueryError = GithubComVeresusTlApiInternalModelErrorResponse


export function useGetIdentUsersId<TData = Awaited<ReturnType<typeof getIdentUsersId>>, TError = GithubComVeresusTlApiInternalModelErrorResponse>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getIdentUsersId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getIdentUsersId>>,
          TError,
          Awaited<ReturnType<typeof getIdentUsersId>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetIdentUsersId<TData = Awaited<ReturnType<typeof getIdentUsersId>>, TError = GithubComVeresusTlApiInternalModelErrorResponse>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getIdentUsersId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getIdentUsersId>>,
          TError,
          Awaited<ReturnType<typeof getIdentUsersId>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetIdentUsersId<TData = Awaited<ReturnType<typeof getIdentUsersId>>, TError = GithubComVeresusTlApiInternalModelErrorResponse>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getIdentUsersId>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Получить пользователя по ID
 */

export function useGetIdentUsersId<TData = Awaited<ReturnType<typeof getIdentUsersId>>, TError = GithubComVeresusTlApiInternalModelErrorResponse>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getIdentUsersId>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetIdentUsersIdQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * Обновляет информацию о пользователе по его ID (int или UUID)
 * @summary Обновить данные пользователя
 */
export const patchIdentUsersId = (
    id: string,
    dtoUserUpdate: DtoUserUpdate,
 ) => {
      
      
      return apiClient<GithubComVeresusTlApiInternalModelMessageResponse>(
      {url: `/ident/users/${id}`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: dtoUserUpdate
    },
      );
    }
  


export const getPatchIdentUsersIdMutationOptions = <TError = GithubComVeresusTlApiInternalModelErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchIdentUsersId>>, TError,{id: string;data: DtoUserUpdate}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof patchIdentUsersId>>, TError,{id: string;data: DtoUserUpdate}, TContext> => {

const mutationKey = ['patchIdentUsersId'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof patchIdentUsersId>>, {id: string;data: DtoUserUpdate}> = (props) => {
          const {id,data} = props ?? {};

          return  patchIdentUsersId(id,data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PatchIdentUsersIdMutationResult = NonNullable<Awaited<ReturnType<typeof patchIdentUsersId>>>
    export type PatchIdentUsersIdMutationBody = DtoUserUpdate
    export type PatchIdentUsersIdMutationError = GithubComVeresusTlApiInternalModelErrorResponse

    /**
 * @summary Обновить данные пользователя
 */
export const usePatchIdentUsersId = <TError = GithubComVeresusTlApiInternalModelErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchIdentUsersId>>, TError,{id: string;data: DtoUserUpdate}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof patchIdentUsersId>>,
        TError,
        {id: string;data: DtoUserUpdate},
        TContext
      > => {

      const mutationOptions = getPatchIdentUsersIdMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Проверяет, существует ли логин в системе
 * @summary Проверка уникальности логина
 */
export const getPublicAuthCheckLoginLogin = (
    login: string,
 signal?: AbortSignal
) => {
      
      
      return apiClient<boolean>(
      {url: `/public/auth/check-login/${login}`, method: 'GET', signal
    },
      );
    }
  



export const getGetPublicAuthCheckLoginLoginQueryKey = (login?: string,) => {
    return [
    `/public/auth/check-login/${login}`
    ] as const;
    }

    
export const getGetPublicAuthCheckLoginLoginQueryOptions = <TData = Awaited<ReturnType<typeof getPublicAuthCheckLoginLogin>>, TError = GetPublicAuthCheckLoginLogin400 | GetPublicAuthCheckLoginLogin500>(login: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPublicAuthCheckLoginLogin>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetPublicAuthCheckLoginLoginQueryKey(login);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getPublicAuthCheckLoginLogin>>> = ({ signal }) => getPublicAuthCheckLoginLogin(login, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(login), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getPublicAuthCheckLoginLogin>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetPublicAuthCheckLoginLoginQueryResult = NonNullable<Awaited<ReturnType<typeof getPublicAuthCheckLoginLogin>>>
export type GetPublicAuthCheckLoginLoginQueryError = GetPublicAuthCheckLoginLogin400 | GetPublicAuthCheckLoginLogin500


export function useGetPublicAuthCheckLoginLogin<TData = Awaited<ReturnType<typeof getPublicAuthCheckLoginLogin>>, TError = GetPublicAuthCheckLoginLogin400 | GetPublicAuthCheckLoginLogin500>(
 login: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPublicAuthCheckLoginLogin>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPublicAuthCheckLoginLogin>>,
          TError,
          Awaited<ReturnType<typeof getPublicAuthCheckLoginLogin>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetPublicAuthCheckLoginLogin<TData = Awaited<ReturnType<typeof getPublicAuthCheckLoginLogin>>, TError = GetPublicAuthCheckLoginLogin400 | GetPublicAuthCheckLoginLogin500>(
 login: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPublicAuthCheckLoginLogin>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPublicAuthCheckLoginLogin>>,
          TError,
          Awaited<ReturnType<typeof getPublicAuthCheckLoginLogin>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetPublicAuthCheckLoginLogin<TData = Awaited<ReturnType<typeof getPublicAuthCheckLoginLogin>>, TError = GetPublicAuthCheckLoginLogin400 | GetPublicAuthCheckLoginLogin500>(
 login: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPublicAuthCheckLoginLogin>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Проверка уникальности логина
 */

export function useGetPublicAuthCheckLoginLogin<TData = Awaited<ReturnType<typeof getPublicAuthCheckLoginLogin>>, TError = GetPublicAuthCheckLoginLogin400 | GetPublicAuthCheckLoginLogin500>(
 login: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPublicAuthCheckLoginLogin>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetPublicAuthCheckLoginLoginQueryOptions(login,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * Входит в систему
 * @summary Входит в систему
 */
export const postPublicAuthLogin = (
    dtoLoginRequest: DtoLoginRequest,
 signal?: AbortSignal
) => {
      
      
      return apiClient<GithubComVeresusTlApiInternalModelMessageResponse>(
      {url: `/public/auth/login`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: dtoLoginRequest, signal
    },
      );
    }
  


export const getPostPublicAuthLoginMutationOptions = <TError = GithubComVeresusTlApiInternalModelErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postPublicAuthLogin>>, TError,{data: DtoLoginRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof postPublicAuthLogin>>, TError,{data: DtoLoginRequest}, TContext> => {

const mutationKey = ['postPublicAuthLogin'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postPublicAuthLogin>>, {data: DtoLoginRequest}> = (props) => {
          const {data} = props ?? {};

          return  postPublicAuthLogin(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostPublicAuthLoginMutationResult = NonNullable<Awaited<ReturnType<typeof postPublicAuthLogin>>>
    export type PostPublicAuthLoginMutationBody = DtoLoginRequest
    export type PostPublicAuthLoginMutationError = GithubComVeresusTlApiInternalModelErrorResponse

    /**
 * @summary Входит в систему
 */
export const usePostPublicAuthLogin = <TError = GithubComVeresusTlApiInternalModelErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postPublicAuthLogin>>, TError,{data: DtoLoginRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postPublicAuthLogin>>,
        TError,
        {data: DtoLoginRequest},
        TContext
      > => {

      const mutationOptions = getPostPublicAuthLoginMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Выходит из системы
 * @summary Выходит из системы
 */
export const postPublicAuthLogout = (
    
 signal?: AbortSignal
) => {
      
      
      return apiClient<GithubComVeresusTlApiInternalModelMessageResponse>(
      {url: `/public/auth/logout`, method: 'POST', signal
    },
      );
    }
  


export const getPostPublicAuthLogoutMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postPublicAuthLogout>>, TError,void, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof postPublicAuthLogout>>, TError,void, TContext> => {

const mutationKey = ['postPublicAuthLogout'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postPublicAuthLogout>>, void> = () => {
          

          return  postPublicAuthLogout()
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostPublicAuthLogoutMutationResult = NonNullable<Awaited<ReturnType<typeof postPublicAuthLogout>>>
    
    export type PostPublicAuthLogoutMutationError = unknown

    /**
 * @summary Выходит из системы
 */
export const usePostPublicAuthLogout = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postPublicAuthLogout>>, TError,void, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postPublicAuthLogout>>,
        TError,
        void,
        TContext
      > => {

      const mutationOptions = getPostPublicAuthLogoutMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Создает нового пользователя в системе
 * @summary Зарегистрировать нового пользователя
 */
export const postPublicAuthRegister = (
    dtoRegisterRequest: DtoRegisterRequest,
 signal?: AbortSignal
) => {
      
      
      return apiClient<GithubComVeresusTlApiInternalModelMessageResponse>(
      {url: `/public/auth/register`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: dtoRegisterRequest, signal
    },
      );
    }
  


export const getPostPublicAuthRegisterMutationOptions = <TError = GithubComVeresusTlApiInternalModelErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postPublicAuthRegister>>, TError,{data: DtoRegisterRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof postPublicAuthRegister>>, TError,{data: DtoRegisterRequest}, TContext> => {

const mutationKey = ['postPublicAuthRegister'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postPublicAuthRegister>>, {data: DtoRegisterRequest}> = (props) => {
          const {data} = props ?? {};

          return  postPublicAuthRegister(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostPublicAuthRegisterMutationResult = NonNullable<Awaited<ReturnType<typeof postPublicAuthRegister>>>
    export type PostPublicAuthRegisterMutationBody = DtoRegisterRequest
    export type PostPublicAuthRegisterMutationError = GithubComVeresusTlApiInternalModelErrorResponse

    /**
 * @summary Зарегистрировать нового пользователя
 */
export const usePostPublicAuthRegister = <TError = GithubComVeresusTlApiInternalModelErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postPublicAuthRegister>>, TError,{data: DtoRegisterRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postPublicAuthRegister>>,
        TError,
        {data: DtoRegisterRequest},
        TContext
      > => {

      const mutationOptions = getPostPublicAuthRegisterMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    