/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * TechLogist API
 * API сервер для управления логистикой
 * OpenAPI spec version: 1.0
 */

/**
 * DTO для передачи данных авторизации
 */
export interface DtoLoginRequest {
  login?: string;
  password?: string;
}
