/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * TechLogist API
 * API сервер для управления логистикой
 * OpenAPI spec version: 1.0
 */

/**
 * Роли пользователей в системе
 */
export type DtoRoleStatic = typeof DtoRoleStatic[keyof typeof DtoRoleStatic];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const DtoRoleStatic = {
  DRIVER: 'driver',
  DISP: 'disp',
  ADMIN: 'admin',
  MAIN_ADMIN: 'mainAdmin',
} as const;
