/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * TechLogist API
 * API сервер для управления логистикой
 * OpenAPI spec version: 1.0
 */

export type GetCheckParams = {
/**
 * Если true — вернуть имя пользователя
 */
is_name?: boolean;
};
