/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * TechLogist API
 * API сервер для управления логистикой
 * OpenAPI spec version: 1.0
 */
import type { GithubComVeresusTlApiInternalClientsTlOrdersClientDtoOrderOutStatus } from './githubComVeresusTlApiInternalClientsTlOrdersClientDtoOrderOutStatus';

export interface GithubComVeresusTlApiInternalClientsTlOrdersClientDtoOrderOut {
  cargo_description?: string;
  cargo_name?: string;
  cargo_type_name?: string;
  cargo_weight?: number;
  depart_loc?: number;
  dispatcher_id?: number;
  driver_id?: number;
  goal_loc?: number;
  id?: number;
  is_urgent?: boolean;
  order_status_name?: GithubComVeresusTlApiInternalClientsTlOrdersClientDtoOrderOutStatus;
  photo_id?: string;
  time?: string;
}
