/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * TechLogist API
 * API сервер для управления логистикой
 * OpenAPI spec version: 1.0
 */

export type GithubComVeresusTlApiInternalModelCheckResponseRole = typeof GithubComVeresusTlApiInternalModelCheckResponseRole[keyof typeof GithubComVeresusTlApiInternalModelCheckResponseRole];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GithubComVeresusTlApiInternalModelCheckResponseRole = {
  driver: 'driver',
  disp: 'disp',
  admin: 'admin',
  mainAdmin: 'mainAdmin',
} as const;
