/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * TL Analytics API
 * API для аналитики заказов
 * OpenAPI spec version: 1.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  GetAnalyticsWorkshopsIncomingParams,
  ModelDepartIncomingResponse,
  ModelErrorResponse
} from '.././model';

import { apiClient } from '../../../utils/customAxiosAnalytic';




/**
 * Возвращает агрегированные данные о поступлении заказов из цехов по типам грузов
 * @summary Получить данные для диаграммы "Поступления из цехов"
 */
export const getAnalyticsWorkshopsIncoming = (
    params: GetAnalyticsWorkshopsIncomingParams,
 signal?: AbortSignal
) => {
      
      
      return apiClient<ModelDepartIncomingResponse[]>(
      {url: `/analytics/workshops/incoming`, method: 'GET',
        params, signal
    },
      );
    }
  



export const getGetAnalyticsWorkshopsIncomingQueryKey = (params?: GetAnalyticsWorkshopsIncomingParams,) => {
    return [
    `/analytics/workshops/incoming`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetAnalyticsWorkshopsIncomingQueryOptions = <TData = Awaited<ReturnType<typeof getAnalyticsWorkshopsIncoming>>, TError = ModelErrorResponse>(params: GetAnalyticsWorkshopsIncomingParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAnalyticsWorkshopsIncoming>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAnalyticsWorkshopsIncomingQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAnalyticsWorkshopsIncoming>>> = ({ signal }) => getAnalyticsWorkshopsIncoming(params, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAnalyticsWorkshopsIncoming>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetAnalyticsWorkshopsIncomingQueryResult = NonNullable<Awaited<ReturnType<typeof getAnalyticsWorkshopsIncoming>>>
export type GetAnalyticsWorkshopsIncomingQueryError = ModelErrorResponse


export function useGetAnalyticsWorkshopsIncoming<TData = Awaited<ReturnType<typeof getAnalyticsWorkshopsIncoming>>, TError = ModelErrorResponse>(
 params: GetAnalyticsWorkshopsIncomingParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAnalyticsWorkshopsIncoming>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAnalyticsWorkshopsIncoming>>,
          TError,
          Awaited<ReturnType<typeof getAnalyticsWorkshopsIncoming>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAnalyticsWorkshopsIncoming<TData = Awaited<ReturnType<typeof getAnalyticsWorkshopsIncoming>>, TError = ModelErrorResponse>(
 params: GetAnalyticsWorkshopsIncomingParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAnalyticsWorkshopsIncoming>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAnalyticsWorkshopsIncoming>>,
          TError,
          Awaited<ReturnType<typeof getAnalyticsWorkshopsIncoming>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAnalyticsWorkshopsIncoming<TData = Awaited<ReturnType<typeof getAnalyticsWorkshopsIncoming>>, TError = ModelErrorResponse>(
 params: GetAnalyticsWorkshopsIncomingParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAnalyticsWorkshopsIncoming>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Получить данные для диаграммы "Поступления из цехов"
 */

export function useGetAnalyticsWorkshopsIncoming<TData = Awaited<ReturnType<typeof getAnalyticsWorkshopsIncoming>>, TError = ModelErrorResponse>(
 params: GetAnalyticsWorkshopsIncomingParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAnalyticsWorkshopsIncoming>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetAnalyticsWorkshopsIncomingQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




