/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * TL Analytics API
 * API для аналитики заказов
 * OpenAPI spec version: 1.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  GetAnalyticsDriversAverageTimeParams,
  GetAnalyticsDriversOrdersByTypesParams,
  GetAnalyticsWorkshopsIncomingByBuildingsParams,
  GetAnalyticsWorkshopsIncomingParams,
  ModelDepartIncomingResponse,
  ModelDriverAverageTimeResponse,
  ModelDriverOrdersResponse,
  ModelErrorResponse
} from '.././model';

import { apiClient } from '../../../utils/customAxiosAnalytic';




/**
 * Возвращает среднее время выполнения заказов для каждого водителя в минутах
 * @summary Получить среднее время выполнения заказов водителями
 */
export const getAnalyticsDriversAverageTime = (
    params: GetAnalyticsDriversAverageTimeParams,
 signal?: AbortSignal
) => {
      
      
      return apiClient<ModelDriverAverageTimeResponse[]>(
      {url: `/analytics/drivers/average-time`, method: 'GET',
        params, signal
    },
      );
    }
  



export const getGetAnalyticsDriversAverageTimeQueryKey = (params?: GetAnalyticsDriversAverageTimeParams,) => {
    return [
    `/analytics/drivers/average-time`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetAnalyticsDriversAverageTimeQueryOptions = <TData = Awaited<ReturnType<typeof getAnalyticsDriversAverageTime>>, TError = ModelErrorResponse>(params: GetAnalyticsDriversAverageTimeParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAnalyticsDriversAverageTime>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAnalyticsDriversAverageTimeQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAnalyticsDriversAverageTime>>> = ({ signal }) => getAnalyticsDriversAverageTime(params, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAnalyticsDriversAverageTime>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetAnalyticsDriversAverageTimeQueryResult = NonNullable<Awaited<ReturnType<typeof getAnalyticsDriversAverageTime>>>
export type GetAnalyticsDriversAverageTimeQueryError = ModelErrorResponse


export function useGetAnalyticsDriversAverageTime<TData = Awaited<ReturnType<typeof getAnalyticsDriversAverageTime>>, TError = ModelErrorResponse>(
 params: GetAnalyticsDriversAverageTimeParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAnalyticsDriversAverageTime>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAnalyticsDriversAverageTime>>,
          TError,
          Awaited<ReturnType<typeof getAnalyticsDriversAverageTime>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAnalyticsDriversAverageTime<TData = Awaited<ReturnType<typeof getAnalyticsDriversAverageTime>>, TError = ModelErrorResponse>(
 params: GetAnalyticsDriversAverageTimeParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAnalyticsDriversAverageTime>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAnalyticsDriversAverageTime>>,
          TError,
          Awaited<ReturnType<typeof getAnalyticsDriversAverageTime>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAnalyticsDriversAverageTime<TData = Awaited<ReturnType<typeof getAnalyticsDriversAverageTime>>, TError = ModelErrorResponse>(
 params: GetAnalyticsDriversAverageTimeParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAnalyticsDriversAverageTime>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Получить среднее время выполнения заказов водителями
 */

export function useGetAnalyticsDriversAverageTime<TData = Awaited<ReturnType<typeof getAnalyticsDriversAverageTime>>, TError = ModelErrorResponse>(
 params: GetAnalyticsDriversAverageTimeParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAnalyticsDriversAverageTime>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetAnalyticsDriversAverageTimeQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * Возвращает агрегированные данные о заказах по водителям и типам груза. Может возвращать количество заказов или вес груза в зависимости от параметра isWithWeight
 * @summary Получить статистику заказов по водителям и типам груза
 */
export const getAnalyticsDriversOrdersByTypes = (
    params: GetAnalyticsDriversOrdersByTypesParams,
 signal?: AbortSignal
) => {
      
      
      return apiClient<ModelDriverOrdersResponse[]>(
      {url: `/analytics/drivers/orders-by-types`, method: 'GET',
        params, signal
    },
      );
    }
  



export const getGetAnalyticsDriversOrdersByTypesQueryKey = (params?: GetAnalyticsDriversOrdersByTypesParams,) => {
    return [
    `/analytics/drivers/orders-by-types`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetAnalyticsDriversOrdersByTypesQueryOptions = <TData = Awaited<ReturnType<typeof getAnalyticsDriversOrdersByTypes>>, TError = ModelErrorResponse>(params: GetAnalyticsDriversOrdersByTypesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAnalyticsDriversOrdersByTypes>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAnalyticsDriversOrdersByTypesQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAnalyticsDriversOrdersByTypes>>> = ({ signal }) => getAnalyticsDriversOrdersByTypes(params, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAnalyticsDriversOrdersByTypes>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetAnalyticsDriversOrdersByTypesQueryResult = NonNullable<Awaited<ReturnType<typeof getAnalyticsDriversOrdersByTypes>>>
export type GetAnalyticsDriversOrdersByTypesQueryError = ModelErrorResponse


export function useGetAnalyticsDriversOrdersByTypes<TData = Awaited<ReturnType<typeof getAnalyticsDriversOrdersByTypes>>, TError = ModelErrorResponse>(
 params: GetAnalyticsDriversOrdersByTypesParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAnalyticsDriversOrdersByTypes>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAnalyticsDriversOrdersByTypes>>,
          TError,
          Awaited<ReturnType<typeof getAnalyticsDriversOrdersByTypes>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAnalyticsDriversOrdersByTypes<TData = Awaited<ReturnType<typeof getAnalyticsDriversOrdersByTypes>>, TError = ModelErrorResponse>(
 params: GetAnalyticsDriversOrdersByTypesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAnalyticsDriversOrdersByTypes>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAnalyticsDriversOrdersByTypes>>,
          TError,
          Awaited<ReturnType<typeof getAnalyticsDriversOrdersByTypes>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAnalyticsDriversOrdersByTypes<TData = Awaited<ReturnType<typeof getAnalyticsDriversOrdersByTypes>>, TError = ModelErrorResponse>(
 params: GetAnalyticsDriversOrdersByTypesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAnalyticsDriversOrdersByTypes>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Получить статистику заказов по водителям и типам груза
 */

export function useGetAnalyticsDriversOrdersByTypes<TData = Awaited<ReturnType<typeof getAnalyticsDriversOrdersByTypes>>, TError = ModelErrorResponse>(
 params: GetAnalyticsDriversOrdersByTypesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAnalyticsDriversOrdersByTypes>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetAnalyticsDriversOrdersByTypesQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * Возвращает агрегированные данные о поступлении заказов из цехов по типам грузов. Если isIn=false - заказы отправленные ИЗ цехов, если isIn=true - заказы отправленные В цеха
 * @summary Получить данные для диаграммы "Поступления из цехов"
 */
export const getAnalyticsWorkshopsIncoming = (
    params: GetAnalyticsWorkshopsIncomingParams,
 signal?: AbortSignal
) => {
      
      
      return apiClient<ModelDepartIncomingResponse[]>(
      {url: `/analytics/workshops/incoming`, method: 'GET',
        params, signal
    },
      );
    }
  



export const getGetAnalyticsWorkshopsIncomingQueryKey = (params?: GetAnalyticsWorkshopsIncomingParams,) => {
    return [
    `/analytics/workshops/incoming`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetAnalyticsWorkshopsIncomingQueryOptions = <TData = Awaited<ReturnType<typeof getAnalyticsWorkshopsIncoming>>, TError = ModelErrorResponse>(params: GetAnalyticsWorkshopsIncomingParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAnalyticsWorkshopsIncoming>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAnalyticsWorkshopsIncomingQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAnalyticsWorkshopsIncoming>>> = ({ signal }) => getAnalyticsWorkshopsIncoming(params, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAnalyticsWorkshopsIncoming>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetAnalyticsWorkshopsIncomingQueryResult = NonNullable<Awaited<ReturnType<typeof getAnalyticsWorkshopsIncoming>>>
export type GetAnalyticsWorkshopsIncomingQueryError = ModelErrorResponse


export function useGetAnalyticsWorkshopsIncoming<TData = Awaited<ReturnType<typeof getAnalyticsWorkshopsIncoming>>, TError = ModelErrorResponse>(
 params: GetAnalyticsWorkshopsIncomingParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAnalyticsWorkshopsIncoming>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAnalyticsWorkshopsIncoming>>,
          TError,
          Awaited<ReturnType<typeof getAnalyticsWorkshopsIncoming>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAnalyticsWorkshopsIncoming<TData = Awaited<ReturnType<typeof getAnalyticsWorkshopsIncoming>>, TError = ModelErrorResponse>(
 params: GetAnalyticsWorkshopsIncomingParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAnalyticsWorkshopsIncoming>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAnalyticsWorkshopsIncoming>>,
          TError,
          Awaited<ReturnType<typeof getAnalyticsWorkshopsIncoming>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAnalyticsWorkshopsIncoming<TData = Awaited<ReturnType<typeof getAnalyticsWorkshopsIncoming>>, TError = ModelErrorResponse>(
 params: GetAnalyticsWorkshopsIncomingParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAnalyticsWorkshopsIncoming>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Получить данные для диаграммы "Поступления из цехов"
 */

export function useGetAnalyticsWorkshopsIncoming<TData = Awaited<ReturnType<typeof getAnalyticsWorkshopsIncoming>>, TError = ModelErrorResponse>(
 params: GetAnalyticsWorkshopsIncomingParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAnalyticsWorkshopsIncoming>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetAnalyticsWorkshopsIncomingQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * Возвращает агрегированные данные о поступлении заказов из цехов по типам грузов с привязкой к корпусам. Название формируется как "название_корпуса-название_цеха". Если isIn=false - заказы отправленные ИЗ цехов, если isIn=true - заказы отправленные В цеха
 * @summary Получить данные для диаграммы "Поступления из цехов" с привязкой к корпусам
 */
export const getAnalyticsWorkshopsIncomingByBuildings = (
    params: GetAnalyticsWorkshopsIncomingByBuildingsParams,
 signal?: AbortSignal
) => {
      
      
      return apiClient<ModelDepartIncomingResponse[]>(
      {url: `/analytics/workshops/incoming-by-buildings`, method: 'GET',
        params, signal
    },
      );
    }
  



export const getGetAnalyticsWorkshopsIncomingByBuildingsQueryKey = (params?: GetAnalyticsWorkshopsIncomingByBuildingsParams,) => {
    return [
    `/analytics/workshops/incoming-by-buildings`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetAnalyticsWorkshopsIncomingByBuildingsQueryOptions = <TData = Awaited<ReturnType<typeof getAnalyticsWorkshopsIncomingByBuildings>>, TError = ModelErrorResponse>(params: GetAnalyticsWorkshopsIncomingByBuildingsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAnalyticsWorkshopsIncomingByBuildings>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAnalyticsWorkshopsIncomingByBuildingsQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAnalyticsWorkshopsIncomingByBuildings>>> = ({ signal }) => getAnalyticsWorkshopsIncomingByBuildings(params, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAnalyticsWorkshopsIncomingByBuildings>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetAnalyticsWorkshopsIncomingByBuildingsQueryResult = NonNullable<Awaited<ReturnType<typeof getAnalyticsWorkshopsIncomingByBuildings>>>
export type GetAnalyticsWorkshopsIncomingByBuildingsQueryError = ModelErrorResponse


export function useGetAnalyticsWorkshopsIncomingByBuildings<TData = Awaited<ReturnType<typeof getAnalyticsWorkshopsIncomingByBuildings>>, TError = ModelErrorResponse>(
 params: GetAnalyticsWorkshopsIncomingByBuildingsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAnalyticsWorkshopsIncomingByBuildings>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAnalyticsWorkshopsIncomingByBuildings>>,
          TError,
          Awaited<ReturnType<typeof getAnalyticsWorkshopsIncomingByBuildings>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAnalyticsWorkshopsIncomingByBuildings<TData = Awaited<ReturnType<typeof getAnalyticsWorkshopsIncomingByBuildings>>, TError = ModelErrorResponse>(
 params: GetAnalyticsWorkshopsIncomingByBuildingsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAnalyticsWorkshopsIncomingByBuildings>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAnalyticsWorkshopsIncomingByBuildings>>,
          TError,
          Awaited<ReturnType<typeof getAnalyticsWorkshopsIncomingByBuildings>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAnalyticsWorkshopsIncomingByBuildings<TData = Awaited<ReturnType<typeof getAnalyticsWorkshopsIncomingByBuildings>>, TError = ModelErrorResponse>(
 params: GetAnalyticsWorkshopsIncomingByBuildingsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAnalyticsWorkshopsIncomingByBuildings>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Получить данные для диаграммы "Поступления из цехов" с привязкой к корпусам
 */

export function useGetAnalyticsWorkshopsIncomingByBuildings<TData = Awaited<ReturnType<typeof getAnalyticsWorkshopsIncomingByBuildings>>, TError = ModelErrorResponse>(
 params: GetAnalyticsWorkshopsIncomingByBuildingsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAnalyticsWorkshopsIncomingByBuildings>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetAnalyticsWorkshopsIncomingByBuildingsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




